# Сингулярное разложение матрицы вещественной матрицы

## Краткая теория и подопытная матрица

Сингулярное разложение матрица A порядка $m \times n$ является разложение вида $А = U \cdot S \cdot V^H$, где:
* S &mdash; диагональная положительно определенная матрица размером $m \times n$, на главной диагонали которой лежат сингулярные числа;
* $U$, $V$ &mdash; унитарные положительно определенные матрицы размером $m \times m$ и $n \times n$, состоящие из левых и правых сингулярных векторов соответственно;
* $^H$ &mdash; эрмитов оператор (транспонирование матрицы плюс комплексное сопряжение ее элементов).

Для вещественной матрицы эрмитово сопряжение суть транспонирование, т.к. комплексное сопряжение вещественного числа не изменяет его.

In [1]:
import html
import numpy as np
np.set_printoptions(precision=4, suppress=True)

In [2]:
# Полезные символы для Ctrl+C, Ctrl+V
print(html.unescape('&#7476;')\
  + html.unescape('&#8901;')\
  + html.unescape('&#7488;'))

ᴴ⋅ᵀ


## Функция numpy.linalg.svd

In [40]:
# Исходная вещественная матрица
A = np.array([[ 2,  0],
              [ 5,  3],
              [-4,  0]])

# Бдыщ!
U, s, Vh = np.linalg.svd(A)

# Матрица из нулей размером с исходную, по главной диагонали которой расположены
# сингулярные числа
S = np.zeros_like(A, dtype=float)
S[np.diag_indices(min(S.shape))] = s

print('Исходная вещественная матрица m x n:\n\n', A)
print('\nРанг исходной матрицы:\n\n', np.linalg.matrix_rank(A))
print('\nОртогональная матрица поворота U размером m x m:\n\n', U)
print('\nМасштабирующая матрица S размером m x n:\n\n', S)
print('\nОртогональная матрица поворота Vᴴ размером n x n:\n\n', Vh)
print('\nПроверим U на ортогональность, вычислив Uᴴ⋅U:\n\n', U.T @ U)
print('\nПроверим Vᴴ на ортогональность, вычислив (Vᴴ)ᴴ⋅Vᴴ:\n\n', Vh.T @ Vh)
print('\nВосстановление исходной матрицы:\n\n', U @ S @ Vh)

Исходная вещественная матрица m x n:

 [[ 2  0]
 [ 5  3]
 [-4  0]]

Ранг исходной матрицы:

 2

Ортогональная матрица поворота U размером m x m:

 [[-0.2648  0.3604  0.8944]
 [-0.8058 -0.5921 -0.    ]
 [ 0.5296 -0.7208  0.4472]]

Масштабирующая матрица S размером m x n:

 [[7.1015 0.    ]
 [0.     1.8892]
 [0.     0.    ]]

Ортогональная матрица поворота Vᴴ размером n x n:

 [[-0.9403 -0.3404]
 [ 0.3404 -0.9403]]

Проверим U на ортогональность, вычислив Uᴴ⋅U:

 [[ 1. -0.  0.]
 [-0.  1. -0.]
 [ 0. -0.  1.]]

Проверим Vᴴ на ортогональность, вычислив (Vᴴ)ᴴ⋅Vᴴ:

 [[ 1. -0.]
 [-0.  1.]]

Восстановление исходной матрицы:

 [[ 2.  0.]
 [ 5.  3.]
 [-4. -0.]]


## Более подробное вычисление

In [41]:
# Спектральное разложение A⋅Aᵀ и Aᵀ⋅A
v_l, S_l = np.linalg.eig(A @ A.T)
v_r, S_r = np.linalg.eig(A.T @ A)

# Сортировка собственных значений и собственных векторов по убыванию первых
idx_l = v_l.argsort()[::-1]
idx_r = v_r.argsort()[::-1]
v_l, S_l = v_l[idx_l], S_l[:, idx_l]
v_r, S_r = v_r[idx_r], S_r[:, idx_r]

# Округление околонулевых значений 0 (особенно важно для значений типа -0.0e-15)
v_l[abs(v_l) < 1e-9] = 0.0
v_r[abs(v_r) < 1e-9] = 0.0

# Сингулярны значения из отсортированых по убыванию собственных значний A⋅Aᵀ
s = np.sqrt(v_r)

# Матрицы U и Vᴴ. Функция np.linalg.eig возвращает матрицу собственных векторов
# так, что собственные векторы записаны в столбцах. Левая сингулярная матрица U
# составляется так, что нормированные и отсортированные собственные векторы A⋅Aᵀ
# образуют ее столбцы, а правая сингулярная матрица V так, что нормированные и
# отсортированные собственные векторы Aᵀ⋅A образуют ее строки. Но в выражение
# сингулярного разложения вещественной матрицы V входит в транспонированном виде
U = S_l
Vh = S_r

print('Исходная вещественная матрица m x n:\n\n', A)
print('\nРанг исходной матрицы:\n\n', np.linalg.matrix_rank(A))
print('\nОртогональная матрица поворота U размером m x m:\n\n', U)
print('\nМасштабирующая матрица S размером m x n:\n\n', S)
print('\nОртогональная матрица поворота Vᴴ размером n x n:\n\n', Vh)
print('\nПроверим U на ортогональность, вычислив Uᴴ⋅U:\n\n', U.T @ U)
print('\nПроверим Vᴴ на ортогональность, вычислив (Vᴴ)ᴴ⋅Vᴴ:\n\n', Vh.T @ Vh)
print('\nВосстановление исходной матрицы:\n\n', U @ S @ Vh)

Исходная вещественная матрица m x n:

 [[ 2  0]
 [ 5  3]
 [-4  0]]

Ранг исходной матрицы:

 2

Ортогональная матрица поворота U размером m x m:

 [[-0.2648 -0.3604 -0.8944]
 [-0.8058  0.5921  0.    ]
 [ 0.5296  0.7208 -0.4472]]

Масштабирующая матрица S размером m x n:

 [[7.1015 0.    ]
 [0.     1.8892]
 [0.     0.    ]]

Ортогональная матрица поворота Vᴴ размером n x n:

 [[ 0.9403 -0.3404]
 [ 0.3404  0.9403]]

Проверим U на ортогональность, вычислив Uᴴ⋅U:

 [[ 1. -0. -0.]
 [-0.  1.  0.]
 [-0.  0.  1.]]

Проверим Vᴴ на ортогональность, вычислив (Vᴴ)ᴴ⋅Vᴴ:

 [[1. 0.]
 [0. 1.]]

Восстановление исходной матрицы:

 [[-2. -0.]
 [-5.  3.]
 [ 4. -0.]]
